// Package epglgo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package epglgo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnit.
const (
	CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnitKG CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnit = "KG"
	CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnitLB CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnit = "LB"
)

// Defines values for CreateUpdateShipmentJSONBodyDetailsDimensionsUnit.
const (
	CreateUpdateShipmentJSONBodyDetailsDimensionsUnitCM CreateUpdateShipmentJSONBodyDetailsDimensionsUnit = "CM"
	CreateUpdateShipmentJSONBodyDetailsDimensionsUnitIN CreateUpdateShipmentJSONBodyDetailsDimensionsUnit = "IN"
)

// Defines values for CreateUpdateShipmentJSONBodyDetailsShippingType.
const (
	DOM CreateUpdateShipmentJSONBodyDetailsShippingType = "DOM"
	INT CreateUpdateShipmentJSONBodyDetailsShippingType = "INT"
)

// Defines values for CreateUpdateShipmentJSONBodyDetailsWeightUnit.
const (
	CreateUpdateShipmentJSONBodyDetailsWeightUnitKG CreateUpdateShipmentJSONBodyDetailsWeightUnit = "KG"
	CreateUpdateShipmentJSONBodyDetailsWeightUnitLB CreateUpdateShipmentJSONBodyDetailsWeightUnit = "LB"
)

// Defines values for CreateUpdateShipmentJSONBodyItemsDimensionsUnit.
const (
	CreateUpdateShipmentJSONBodyItemsDimensionsUnitCM CreateUpdateShipmentJSONBodyItemsDimensionsUnit = "CM"
	CreateUpdateShipmentJSONBodyItemsDimensionsUnitIN CreateUpdateShipmentJSONBodyItemsDimensionsUnit = "IN"
)

// Defines values for CreateUpdateShipmentJSONBodyItemsWeightUnit.
const (
	CreateUpdateShipmentJSONBodyItemsWeightUnitKG CreateUpdateShipmentJSONBodyItemsWeightUnit = "KG"
	CreateUpdateShipmentJSONBodyItemsWeightUnitLB CreateUpdateShipmentJSONBodyItemsWeightUnit = "LB"
)

// Defines values for CreateShipmentInvoiceJSONBodyChargeableWeightUnit.
const (
	CreateShipmentInvoiceJSONBodyChargeableWeightUnitKG CreateShipmentInvoiceJSONBodyChargeableWeightUnit = "KG"
	CreateShipmentInvoiceJSONBodyChargeableWeightUnitLB CreateShipmentInvoiceJSONBodyChargeableWeightUnit = "LB"
)

// AuthenticateClientJSONBody defines parameters for AuthenticateClient.
type AuthenticateClientJSONBody struct {
	// ClientId The client ID.
	ClientId string `json:"clientId"`

	// ClientSecret The client secret.
	ClientSecret string `json:"clientSecret"`
}

// CreateUpdateShipmentJSONBody defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBody struct {
	// Details Represents the detailed information about a shipment.
	Details struct {
		// Cod Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
		Cod *struct {
			// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
			Amount float32 `json:"amount"`

			// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
			CurrencyCode string `json:"currencyCode"`
		} `json:"cod,omitempty"`

		// Customs Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
		Customs *struct {
			// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
			Amount float32 `json:"amount"`

			// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
			CurrencyCode string `json:"currencyCode"`
		} `json:"customs,omitempty"`

		// DeclaredWeight The weight used for billing purposes to charge your customer.
		DeclaredWeight struct {
			// Unit The unit of measurement used for the weight of the Shipment.
			Unit CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnit `json:"unit"`

			// Value The weight value.
			Value float32 `json:"value"`
		} `json:"declaredWeight"`

		// DeliveryAttempts The number of delivery attempts.
		DeliveryAttempts *int `json:"deliveryAttempts,omitempty"`

		// DeliveryCharges Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
		DeliveryCharges *struct {
			// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
			Amount float32 `json:"amount"`

			// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
			CurrencyCode string `json:"currencyCode"`
		} `json:"deliveryCharges,omitempty"`

		// DeliveryDate The date on which the shipment was actually delivered.
		DeliveryDate *time.Time `json:"deliveryDate,omitempty"`

		// DeliveryStatus The current status of the shipment.
		DeliveryStatus *string `json:"deliveryStatus,omitempty"`

		// DescriptionOfGoods Provides a detailed description of the items in the shipment.
		DescriptionOfGoods string `json:"descriptionOfGoods"`

		// Dimensions Represents the dimensions of an object, including length, width, height, and the unit of measurement.
		Dimensions *struct {
			// Height Height must be greater than 0 and less than 99999.
			Height float64 `json:"height"`

			// Length Length must be greater than 0 and less than 99999.
			Length float64 `json:"length"`

			// Unit The unit of measurement for the dimensions. Must be exactly 2 characters and either "CM" or "IN".
			Unit CreateUpdateShipmentJSONBodyDetailsDimensionsUnit `json:"unit"`

			// Width Width must be greater than 0 and less than 99999.
			Width float64 `json:"width"`
		} `json:"dimensions,omitempty"`

		// HsCodeDescription Describes the goods based on the Harmonized System (HS) code, used for international trade classification.
		HsCodeDescription *string `json:"hsCodeDescription,omitempty"`

		// NumberOfPieces The total count of individual items or packages in the shipment.
		NumberOfPieces int `json:"numberOfPieces"`

		// PickupDate The date on which the shipment was collected.
		PickupDate time.Time `json:"pickupDate"`

		// ProductCategory Defines the shipment category, such as Documents and Non-Documents.
		ProductCategory string `json:"productCategory"`

		// ProductType Represents the service level of the shipment, such as Non-Priority, Standard, Priority, Premium, Same Day, Next Day, etc.
		ProductType string `json:"productType"`

		// ShippingType Specifies whether the shipment is Domestic or International.
		ShippingType CreateUpdateShipmentJSONBodyDetailsShippingType `json:"shippingType"`

		// Weight The weight provided by the customer or the volumetric or gross weight, whichever is higher.
		Weight struct {
			// Unit The unit of measurement used for the weight of the Shipment.
			Unit CreateUpdateShipmentJSONBodyDetailsWeightUnit `json:"unit"`

			// Value The weight value.
			Value float32 `json:"value"`
		} `json:"weight"`
	} `json:"details"`

	// Items The details of the items contained in the shipment.
	Items *[]struct {
		// CountryOfOrigin The country where the item was manufactured.
		CountryOfOrigin *string `json:"countryOfOrigin,omitempty"`

		// CustomsValue Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
		CustomsValue *struct {
			// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
			Amount float32 `json:"amount"`

			// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
			CurrencyCode string `json:"currencyCode"`
		} `json:"customsValue,omitempty"`

		// Description A brief summary of the item's features or nature.
		Description *string `json:"description,omitempty"`

		// Dimensions Represents the dimensions of an object, including length, width, height, and the unit of measurement.
		Dimensions *struct {
			// Height Height must be greater than 0 and less than 99999.
			Height float64 `json:"height"`

			// Length Length must be greater than 0 and less than 99999.
			Length float64 `json:"length"`

			// Unit The unit of measurement for the dimensions. Must be exactly 2 characters and either "CM" or "IN".
			Unit CreateUpdateShipmentJSONBodyItemsDimensionsUnit `json:"unit"`

			// Width Width must be greater than 0 and less than 99999.
			Width float64 `json:"width"`
		} `json:"dimensions,omitempty"`

		// HsCode The Harmonized System code used for classifying goods in international trade.
		HsCode *string `json:"hsCode,omitempty"`

		// Quantity The number of units of a specific item.
		Quantity *float32 `json:"quantity,omitempty"`

		// Weight The weight of the Shipment.
		Weight *struct {
			// Unit The unit of measurement used for the weight of the Shipment.
			Unit CreateUpdateShipmentJSONBodyItemsWeightUnit `json:"unit"`

			// Value The weight value.
			Value float32 `json:"value"`
		} `json:"weight,omitempty"`
	} `json:"items,omitempty"`

	// Receiver Represents the contact and address details of the receiver.
	Receiver struct {
		// City The city name of the address.
		City string `json:"city"`

		// CountryCode The country code of the address, typically in ISO 3166-1 alpha-2 format. For a full list of country codes, see the ISO website www.iso.org/obp/ui/#search
		CountryCode string `json:"countryCode"`

		// Email The email address of the person or company receiving the shipment.
		Email *string `json:"email,omitempty"`

		// Line1 The first line of the address, typically including street name and number.
		Line1 *string `json:"line1,omitempty"`

		// Line2 The second line of the address, typically used for additional information such as apartment or suite number.
		Line2 *string `json:"line2,omitempty"`

		// Line3 The third line of the address, often used for further details if needed.
		Line3 *string `json:"line3,omitempty"`

		// Name The name of the person or company receiving the shipment.
		Name string `json:"name"`

		// Phone The phone number of the person or company receiving the shipment. The phone number should be in international format, starting with a + followed by the country code, then the area code and local number.
		Phone string `json:"phone"`

		// PostCode The postal code or Zip Code of the address.
		PostCode *string `json:"postCode,omitempty"`

		// SecondPhone An additional phone number of the person or company receiving the shipment.
		SecondPhone *string `json:"secondPhone,omitempty"`

		// State The state or region of the address.
		State *string `json:"state,omitempty"`
	} `json:"receiver"`

	// Sender Represents the contact and address details of the sender.
	Sender struct {
		// City The city name of the address.
		City string `json:"city"`

		// CountryCode The country code of the address, typically in ISO 3166-1 alpha-2 format. For a full list of country codes, see the ISO website www.iso.org/obp/ui/#search
		CountryCode string `json:"countryCode"`

		// Email The email address of the person or company sending the shipment.
		Email *string `json:"email,omitempty"`

		// Line1 The first line of the address, typically including street name and number.
		Line1 *string `json:"line1,omitempty"`

		// Line2 The second line of the address, typically used for additional information such as apartment or suite number.
		Line2 *string `json:"line2,omitempty"`

		// Line3 The third line of the address, often used for further details if needed.
		Line3 *string `json:"line3,omitempty"`

		// Name The name of the person or company sending the shipment.
		Name string `json:"name"`

		// Phone The phone number of the person or company sending the shipment. The phone number should be in international format, starting with a + followed by the country code, then the area code and local number.
		Phone string `json:"phone"`

		// PostCode The postal code or ZIP code of the address.
		PostCode *string `json:"postCode,omitempty"`

		// SecondPhone An additional phone number of the person or company sending the shipment.
		SecondPhone *string `json:"secondPhone,omitempty"`

		// State The state or region of the address.
		State *string `json:"state,omitempty"`
	} `json:"sender"`

	// TrackingNumber A unique code assigned by the shipping company to monitor and trace the shipment’s progress.
	TrackingNumber string `json:"trackingNumber"`
}

// CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnit defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBodyDetailsDeclaredWeightUnit string

// CreateUpdateShipmentJSONBodyDetailsDimensionsUnit defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBodyDetailsDimensionsUnit string

// CreateUpdateShipmentJSONBodyDetailsShippingType defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBodyDetailsShippingType string

// CreateUpdateShipmentJSONBodyDetailsWeightUnit defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBodyDetailsWeightUnit string

// CreateUpdateShipmentJSONBodyItemsDimensionsUnit defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBodyItemsDimensionsUnit string

// CreateUpdateShipmentJSONBodyItemsWeightUnit defines parameters for CreateUpdateShipment.
type CreateUpdateShipmentJSONBodyItemsWeightUnit string

// CreateShipmentInvoiceJSONBody defines parameters for CreateShipmentInvoice.
type CreateShipmentInvoiceJSONBody struct {
	// ChargeableWeight The weight of the Shipment.
	ChargeableWeight struct {
		// Unit The unit of measurement used for the weight of the Shipment.
		Unit CreateShipmentInvoiceJSONBodyChargeableWeightUnit `json:"unit"`

		// Value The weight value.
		Value float32 `json:"value"`
	} `json:"chargeableWeight"`

	// Charges The list of charges associated with the shipment.
	Charges []struct {
		// Amount Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
		Amount struct {
			// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
			Amount float32 `json:"amount"`

			// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
			CurrencyCode string `json:"currencyCode"`
		} `json:"amount"`

		// Type The type of the charge. All applicable costs associated with the Shipment. Possible values are; Base Rate, fuel Surcharge, insurance, War risk, handling and packing fees, and other charges. It can not exceed 100 characters
		Type string `json:"type"`
	} `json:"charges"`

	// Invoice Represents the details of an invoice.
	Invoice struct {
		// BillingAccountName The billing account name associated with the invoice. Must not exceed 500 characters.
		BillingAccountName string `json:"billingAccountName"`

		// BillingAccountNumber The billing account number associated with the invoice. Must not exceed 100 characters.
		BillingAccountNumber string `json:"billingAccountNumber"`

		// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters and valid.
		CurrencyCode string `json:"currencyCode"`

		// InvoiceDate The date and time of the invoice.
		InvoiceDate time.Time `json:"invoiceDate"`

		// InvoiceNumber The invoice number of the shipment. Must not exceed 100 characters.
		InvoiceNumber string `json:"invoiceNumber"`

		// TaxAmount The tax amount applied to the invoice. Must be 0 or more.
		TaxAmount float32 `json:"taxAmount"`

		// TotalAmountIncludingTax The total amount including tax for the invoice. Must be 0 or more and greater than the TaxAmount.
		TotalAmountIncludingTax float32 `json:"totalAmountIncludingTax"`

		// TotalDiscountAmount The total discount amount applied to the invoice. Must be 0 or more.
		TotalDiscountAmount *float32 `json:"totalDiscountAmount,omitempty"`
	} `json:"invoice"`

	// TrackingNumber The unique tracking number associated with the shipment.
	TrackingNumber string `json:"trackingNumber"`
}

// CreateShipmentInvoiceJSONBodyChargeableWeightUnit defines parameters for CreateShipmentInvoice.
type CreateShipmentInvoiceJSONBodyChargeableWeightUnit string

// AuthenticateClientJSONRequestBody defines body for AuthenticateClient for application/json ContentType.
type AuthenticateClientJSONRequestBody AuthenticateClientJSONBody

// CreateUpdateShipmentJSONRequestBody defines body for CreateUpdateShipment for application/json ContentType.
type CreateUpdateShipmentJSONRequestBody CreateUpdateShipmentJSONBody

// CreateShipmentInvoiceJSONRequestBody defines body for CreateShipmentInvoice for application/json ContentType.
type CreateShipmentInvoiceJSONRequestBody CreateShipmentInvoiceJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AuthenticateClientWithBody request with any body
	AuthenticateClientWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AuthenticateClient(ctx context.Context, body AuthenticateClientJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUpdateShipmentWithBody request with any body
	CreateUpdateShipmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUpdateShipment(ctx context.Context, body CreateUpdateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateShipmentInvoiceWithBody request with any body
	CreateShipmentInvoiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateShipmentInvoice(ctx context.Context, body CreateShipmentInvoiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AuthenticateClientWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthenticateClientRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthenticateClient(ctx context.Context, body AuthenticateClientJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthenticateClientRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUpdateShipmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUpdateShipmentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUpdateShipment(ctx context.Context, body CreateUpdateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUpdateShipmentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateShipmentInvoiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateShipmentInvoiceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateShipmentInvoice(ctx context.Context, body CreateShipmentInvoiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateShipmentInvoiceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthenticateClientRequest calls the generic AuthenticateClient builder with application/json body
func NewAuthenticateClientRequest(server string, body AuthenticateClientJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAuthenticateClientRequestWithBody(server, "application/json", bodyReader)
}

// NewAuthenticateClientRequestWithBody generates requests for AuthenticateClient with any type of body
func NewAuthenticateClientRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/authenticate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateUpdateShipmentRequest calls the generic CreateUpdateShipment builder with application/json body
func NewCreateUpdateShipmentRequest(server string, body CreateUpdateShipmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUpdateShipmentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateUpdateShipmentRequestWithBody generates requests for CreateUpdateShipment with any type of body
func NewCreateUpdateShipmentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/shipment/create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateShipmentInvoiceRequest calls the generic CreateShipmentInvoice builder with application/json body
func NewCreateShipmentInvoiceRequest(server string, body CreateShipmentInvoiceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateShipmentInvoiceRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateShipmentInvoiceRequestWithBody generates requests for CreateShipmentInvoice with any type of body
func NewCreateShipmentInvoiceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/shipment/issueInvoice")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AuthenticateClientWithBodyWithResponse request with any body
	AuthenticateClientWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthenticateClientResponse, error)

	AuthenticateClientWithResponse(ctx context.Context, body AuthenticateClientJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthenticateClientResponse, error)

	// CreateUpdateShipmentWithBodyWithResponse request with any body
	CreateUpdateShipmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUpdateShipmentResponse, error)

	CreateUpdateShipmentWithResponse(ctx context.Context, body CreateUpdateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUpdateShipmentResponse, error)

	// CreateShipmentInvoiceWithBodyWithResponse request with any body
	CreateShipmentInvoiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateShipmentInvoiceResponse, error)

	CreateShipmentInvoiceWithResponse(ctx context.Context, body CreateShipmentInvoiceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateShipmentInvoiceResponse, error)
}

type AuthenticateClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// AccessToken The JWT token.
		AccessToken string `json:"accessToken"`

		// ExpiresIn The number of seconds until the token expires.
		ExpiresIn int `json:"expiresIn"`

		// TokenType The type of the token, typically "bearer".
		TokenType string `json:"tokenType"`
	}
	JSON401 *string
}

// Status returns HTTPResponse.Status
func (r AuthenticateClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthenticateClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUpdateShipmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		// Details Represents the detailed information about a shipment.
		Details struct {
			// Cod Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
			Cod *struct {
				// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
				Amount float32 `json:"amount"`

				// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
				CurrencyCode string `json:"currencyCode"`
			} `json:"cod,omitempty"`

			// Customs Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
			Customs *struct {
				// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
				Amount float32 `json:"amount"`

				// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
				CurrencyCode string `json:"currencyCode"`
			} `json:"customs,omitempty"`

			// DeclaredWeight The weight used for billing purposes to charge your customer.
			DeclaredWeight struct {
				// Unit The unit of measurement used for the weight of the Shipment.
				Unit CreateUpdateShipment201DetailsDeclaredWeightUnit `json:"unit"`

				// Value The weight value.
				Value float32 `json:"value"`
			} `json:"declaredWeight"`

			// DeliveryAttempts The number of delivery attempts.
			DeliveryAttempts *int `json:"deliveryAttempts,omitempty"`

			// DeliveryCharges Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
			DeliveryCharges *struct {
				// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
				Amount float32 `json:"amount"`

				// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
				CurrencyCode string `json:"currencyCode"`
			} `json:"deliveryCharges,omitempty"`

			// DeliveryDate The date on which the shipment was actually delivered.
			DeliveryDate *time.Time `json:"deliveryDate,omitempty"`

			// DeliveryStatus The current status of the shipment.
			DeliveryStatus *string `json:"deliveryStatus,omitempty"`

			// DescriptionOfGoods Provides a detailed description of the items in the shipment.
			DescriptionOfGoods string `json:"descriptionOfGoods"`

			// Dimensions Represents the dimensions of an object, including length, width, height, and the unit of measurement.
			Dimensions *struct {
				// Height Height must be greater than 0 and less than 99999.
				Height float64 `json:"height"`

				// Length Length must be greater than 0 and less than 99999.
				Length float64 `json:"length"`

				// Unit The unit of measurement for the dimensions. Must be exactly 2 characters and either "CM" or "IN".
				Unit CreateUpdateShipment201DetailsDimensionsUnit `json:"unit"`

				// Width Width must be greater than 0 and less than 99999.
				Width float64 `json:"width"`
			} `json:"dimensions,omitempty"`

			// HsCodeDescription Describes the goods based on the Harmonized System (HS) code, used for international trade classification.
			HsCodeDescription *string `json:"hsCodeDescription,omitempty"`

			// NumberOfPieces The total count of individual items or packages in the shipment.
			NumberOfPieces int `json:"numberOfPieces"`

			// PickupDate The date on which the shipment was collected.
			PickupDate time.Time `json:"pickupDate"`

			// ProductCategory Defines the shipment category, such as Documents and Non-Documents.
			ProductCategory string `json:"productCategory"`

			// ProductType Represents the service level of the shipment, such as Non-Priority, Standard, Priority, Premium, Same Day, Next Day, etc.
			ProductType string `json:"productType"`

			// ShippingType Specifies whether the shipment is Domestic or International.
			ShippingType CreateUpdateShipment201DetailsShippingType `json:"shippingType"`

			// Weight The weight provided by the customer or the volumetric or gross weight, whichever is higher.
			Weight struct {
				// Unit The unit of measurement used for the weight of the Shipment.
				Unit CreateUpdateShipment201DetailsWeightUnit `json:"unit"`

				// Value The weight value.
				Value float32 `json:"value"`
			} `json:"weight"`
		} `json:"details"`

		// Items The details of the items contained in the shipment.
		Items *[]struct {
			// CountryOfOrigin The country where the item was manufactured.
			CountryOfOrigin *string `json:"countryOfOrigin,omitempty"`

			// CustomsValue Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
			CustomsValue *struct {
				// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
				Amount float32 `json:"amount"`

				// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
				CurrencyCode string `json:"currencyCode"`
			} `json:"customsValue,omitempty"`

			// Description A brief summary of the item's features or nature.
			Description *string `json:"description,omitempty"`

			// Dimensions Represents the dimensions of an object, including length, width, height, and the unit of measurement.
			Dimensions *struct {
				// Height Height must be greater than 0 and less than 99999.
				Height float64 `json:"height"`

				// Length Length must be greater than 0 and less than 99999.
				Length float64 `json:"length"`

				// Unit The unit of measurement for the dimensions. Must be exactly 2 characters and either "CM" or "IN".
				Unit CreateUpdateShipment201ItemsDimensionsUnit `json:"unit"`

				// Width Width must be greater than 0 and less than 99999.
				Width float64 `json:"width"`
			} `json:"dimensions,omitempty"`

			// HsCode The Harmonized System code used for classifying goods in international trade.
			HsCode *string `json:"hsCode,omitempty"`

			// Quantity The number of units of a specific item.
			Quantity *float32 `json:"quantity,omitempty"`

			// Weight The weight of the Shipment.
			Weight *struct {
				// Unit The unit of measurement used for the weight of the Shipment.
				Unit CreateUpdateShipment201ItemsWeightUnit `json:"unit"`

				// Value The weight value.
				Value float32 `json:"value"`
			} `json:"weight,omitempty"`
		} `json:"items,omitempty"`

		// Receiver Represents the contact and address details of the receiver.
		Receiver struct {
			// City The city name of the address.
			City string `json:"city"`

			// CountryCode The country code of the address, typically in ISO 3166-1 alpha-2 format. For a full list of country codes, see the ISO website www.iso.org/obp/ui/#search
			CountryCode string `json:"countryCode"`

			// Email The email address of the person or company receiving the shipment.
			Email *string `json:"email,omitempty"`

			// Line1 The first line of the address, typically including street name and number.
			Line1 *string `json:"line1,omitempty"`

			// Line2 The second line of the address, typically used for additional information such as apartment or suite number.
			Line2 *string `json:"line2,omitempty"`

			// Line3 The third line of the address, often used for further details if needed.
			Line3 *string `json:"line3,omitempty"`

			// Name The name of the person or company receiving the shipment.
			Name string `json:"name"`

			// Phone The phone number of the person or company receiving the shipment. The phone number should be in international format, starting with a + followed by the country code, then the area code and local number.
			Phone string `json:"phone"`

			// PostCode The postal code or Zip Code of the address.
			PostCode *string `json:"postCode,omitempty"`

			// SecondPhone An additional phone number of the person or company receiving the shipment.
			SecondPhone *string `json:"secondPhone,omitempty"`

			// State The state or region of the address.
			State *string `json:"state,omitempty"`
		} `json:"receiver"`

		// Sender Represents the contact and address details of the sender.
		Sender struct {
			// City The city name of the address.
			City string `json:"city"`

			// CountryCode The country code of the address, typically in ISO 3166-1 alpha-2 format. For a full list of country codes, see the ISO website www.iso.org/obp/ui/#search
			CountryCode string `json:"countryCode"`

			// Email The email address of the person or company sending the shipment.
			Email *string `json:"email,omitempty"`

			// Line1 The first line of the address, typically including street name and number.
			Line1 *string `json:"line1,omitempty"`

			// Line2 The second line of the address, typically used for additional information such as apartment or suite number.
			Line2 *string `json:"line2,omitempty"`

			// Line3 The third line of the address, often used for further details if needed.
			Line3 *string `json:"line3,omitempty"`

			// Name The name of the person or company sending the shipment.
			Name string `json:"name"`

			// Phone The phone number of the person or company sending the shipment. The phone number should be in international format, starting with a + followed by the country code, then the area code and local number.
			Phone string `json:"phone"`

			// PostCode The postal code or ZIP code of the address.
			PostCode *string `json:"postCode,omitempty"`

			// SecondPhone An additional phone number of the person or company sending the shipment.
			SecondPhone *string `json:"secondPhone,omitempty"`

			// State The state or region of the address.
			State *string `json:"state,omitempty"`
		} `json:"sender"`

		// TrackingNumber A unique code assigned by the shipping company to monitor and trace the shipment’s progress.
		TrackingNumber string `json:"trackingNumber"`
	}
	JSON400 *struct {
		Errors *map[string][]string `json:"errors,omitempty"`
	}
}
type CreateUpdateShipment201DetailsDeclaredWeightUnit string
type CreateUpdateShipment201DetailsDimensionsUnit string
type CreateUpdateShipment201DetailsShippingType string
type CreateUpdateShipment201DetailsWeightUnit string
type CreateUpdateShipment201ItemsDimensionsUnit string
type CreateUpdateShipment201ItemsWeightUnit string

// Status returns HTTPResponse.Status
func (r CreateUpdateShipmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUpdateShipmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateShipmentInvoiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		// ChargeableWeight The weight of the Shipment.
		ChargeableWeight struct {
			// Unit The unit of measurement used for the weight of the Shipment.
			Unit CreateShipmentInvoice201ChargeableWeightUnit `json:"unit"`

			// Value The weight value.
			Value float32 `json:"value"`
		} `json:"chargeableWeight"`

		// Charges The list of charges associated with the shipment.
		Charges []struct {
			// Amount Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
			Amount struct {
				// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
				Amount float32 `json:"amount"`

				// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
				CurrencyCode string `json:"currencyCode"`
			} `json:"amount"`

			// Type The type of the charge. All applicable costs associated with the Shipment. Possible values are; Base Rate, fuel Surcharge, insurance, War risk, handling and packing fees, and other charges. It can not exceed 100 characters
			Type string `json:"type"`
		} `json:"charges"`

		// Invoice Represents the details of an invoice.
		Invoice struct {
			// BillingAccountName The billing account name associated with the invoice. Must not exceed 500 characters.
			BillingAccountName string `json:"billingAccountName"`

			// BillingAccountNumber The billing account number associated with the invoice. Must not exceed 100 characters.
			BillingAccountNumber string `json:"billingAccountNumber"`

			// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters and valid.
			CurrencyCode string `json:"currencyCode"`

			// InvoiceDate The date and time of the invoice.
			InvoiceDate time.Time `json:"invoiceDate"`

			// InvoiceNumber The invoice number of the shipment. Must not exceed 100 characters.
			InvoiceNumber string `json:"invoiceNumber"`

			// TaxAmount The tax amount applied to the invoice. Must be 0 or more.
			TaxAmount float32 `json:"taxAmount"`

			// TotalAmountIncludingTax The total amount including tax for the invoice. Must be 0 or more and greater than the TaxAmount.
			TotalAmountIncludingTax float32 `json:"totalAmountIncludingTax"`

			// TotalDiscountAmount The total discount amount applied to the invoice. Must be 0 or more.
			TotalDiscountAmount *float32 `json:"totalDiscountAmount,omitempty"`
		} `json:"invoice"`

		// TrackingNumber The unique tracking number associated with the shipment.
		TrackingNumber string `json:"trackingNumber"`
	}
	JSON400 *struct {
		Errors  *map[string][]string `json:"errors,omitempty"`
		Message *string              `json:"message,omitempty"`
	}
}
type CreateShipmentInvoice201ChargeableWeightUnit string

// Status returns HTTPResponse.Status
func (r CreateShipmentInvoiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateShipmentInvoiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AuthenticateClientWithBodyWithResponse request with arbitrary body returning *AuthenticateClientResponse
func (c *ClientWithResponses) AuthenticateClientWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthenticateClientResponse, error) {
	rsp, err := c.AuthenticateClientWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthenticateClientResponse(rsp)
}

func (c *ClientWithResponses) AuthenticateClientWithResponse(ctx context.Context, body AuthenticateClientJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthenticateClientResponse, error) {
	rsp, err := c.AuthenticateClient(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthenticateClientResponse(rsp)
}

// CreateUpdateShipmentWithBodyWithResponse request with arbitrary body returning *CreateUpdateShipmentResponse
func (c *ClientWithResponses) CreateUpdateShipmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUpdateShipmentResponse, error) {
	rsp, err := c.CreateUpdateShipmentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUpdateShipmentResponse(rsp)
}

func (c *ClientWithResponses) CreateUpdateShipmentWithResponse(ctx context.Context, body CreateUpdateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUpdateShipmentResponse, error) {
	rsp, err := c.CreateUpdateShipment(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUpdateShipmentResponse(rsp)
}

// CreateShipmentInvoiceWithBodyWithResponse request with arbitrary body returning *CreateShipmentInvoiceResponse
func (c *ClientWithResponses) CreateShipmentInvoiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateShipmentInvoiceResponse, error) {
	rsp, err := c.CreateShipmentInvoiceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateShipmentInvoiceResponse(rsp)
}

func (c *ClientWithResponses) CreateShipmentInvoiceWithResponse(ctx context.Context, body CreateShipmentInvoiceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateShipmentInvoiceResponse, error) {
	rsp, err := c.CreateShipmentInvoice(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateShipmentInvoiceResponse(rsp)
}

// ParseAuthenticateClientResponse parses an HTTP response from a AuthenticateClientWithResponse call
func ParseAuthenticateClientResponse(rsp *http.Response) (*AuthenticateClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthenticateClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// AccessToken The JWT token.
			AccessToken string `json:"accessToken"`

			// ExpiresIn The number of seconds until the token expires.
			ExpiresIn int `json:"expiresIn"`

			// TokenType The type of the token, typically "bearer".
			TokenType string `json:"tokenType"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseCreateUpdateShipmentResponse parses an HTTP response from a CreateUpdateShipmentWithResponse call
func ParseCreateUpdateShipmentResponse(rsp *http.Response) (*CreateUpdateShipmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUpdateShipmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// Details Represents the detailed information about a shipment.
			Details struct {
				// Cod Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
				Cod *struct {
					// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
					Amount float32 `json:"amount"`

					// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
					CurrencyCode string `json:"currencyCode"`
				} `json:"cod,omitempty"`

				// Customs Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
				Customs *struct {
					// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
					Amount float32 `json:"amount"`

					// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
					CurrencyCode string `json:"currencyCode"`
				} `json:"customs,omitempty"`

				// DeclaredWeight The weight used for billing purposes to charge your customer.
				DeclaredWeight struct {
					// Unit The unit of measurement used for the weight of the Shipment.
					Unit CreateUpdateShipment201DetailsDeclaredWeightUnit `json:"unit"`

					// Value The weight value.
					Value float32 `json:"value"`
				} `json:"declaredWeight"`

				// DeliveryAttempts The number of delivery attempts.
				DeliveryAttempts *int `json:"deliveryAttempts,omitempty"`

				// DeliveryCharges Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
				DeliveryCharges *struct {
					// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
					Amount float32 `json:"amount"`

					// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
					CurrencyCode string `json:"currencyCode"`
				} `json:"deliveryCharges,omitempty"`

				// DeliveryDate The date on which the shipment was actually delivered.
				DeliveryDate *time.Time `json:"deliveryDate,omitempty"`

				// DeliveryStatus The current status of the shipment.
				DeliveryStatus *string `json:"deliveryStatus,omitempty"`

				// DescriptionOfGoods Provides a detailed description of the items in the shipment.
				DescriptionOfGoods string `json:"descriptionOfGoods"`

				// Dimensions Represents the dimensions of an object, including length, width, height, and the unit of measurement.
				Dimensions *struct {
					// Height Height must be greater than 0 and less than 99999.
					Height float64 `json:"height"`

					// Length Length must be greater than 0 and less than 99999.
					Length float64 `json:"length"`

					// Unit The unit of measurement for the dimensions. Must be exactly 2 characters and either "CM" or "IN".
					Unit CreateUpdateShipment201DetailsDimensionsUnit `json:"unit"`

					// Width Width must be greater than 0 and less than 99999.
					Width float64 `json:"width"`
				} `json:"dimensions,omitempty"`

				// HsCodeDescription Describes the goods based on the Harmonized System (HS) code, used for international trade classification.
				HsCodeDescription *string `json:"hsCodeDescription,omitempty"`

				// NumberOfPieces The total count of individual items or packages in the shipment.
				NumberOfPieces int `json:"numberOfPieces"`

				// PickupDate The date on which the shipment was collected.
				PickupDate time.Time `json:"pickupDate"`

				// ProductCategory Defines the shipment category, such as Documents and Non-Documents.
				ProductCategory string `json:"productCategory"`

				// ProductType Represents the service level of the shipment, such as Non-Priority, Standard, Priority, Premium, Same Day, Next Day, etc.
				ProductType string `json:"productType"`

				// ShippingType Specifies whether the shipment is Domestic or International.
				ShippingType CreateUpdateShipment201DetailsShippingType `json:"shippingType"`

				// Weight The weight provided by the customer or the volumetric or gross weight, whichever is higher.
				Weight struct {
					// Unit The unit of measurement used for the weight of the Shipment.
					Unit CreateUpdateShipment201DetailsWeightUnit `json:"unit"`

					// Value The weight value.
					Value float32 `json:"value"`
				} `json:"weight"`
			} `json:"details"`

			// Items The details of the items contained in the shipment.
			Items *[]struct {
				// CountryOfOrigin The country where the item was manufactured.
				CountryOfOrigin *string `json:"countryOfOrigin,omitempty"`

				// CustomsValue Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
				CustomsValue *struct {
					// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
					Amount float32 `json:"amount"`

					// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
					CurrencyCode string `json:"currencyCode"`
				} `json:"customsValue,omitempty"`

				// Description A brief summary of the item's features or nature.
				Description *string `json:"description,omitempty"`

				// Dimensions Represents the dimensions of an object, including length, width, height, and the unit of measurement.
				Dimensions *struct {
					// Height Height must be greater than 0 and less than 99999.
					Height float64 `json:"height"`

					// Length Length must be greater than 0 and less than 99999.
					Length float64 `json:"length"`

					// Unit The unit of measurement for the dimensions. Must be exactly 2 characters and either "CM" or "IN".
					Unit CreateUpdateShipment201ItemsDimensionsUnit `json:"unit"`

					// Width Width must be greater than 0 and less than 99999.
					Width float64 `json:"width"`
				} `json:"dimensions,omitempty"`

				// HsCode The Harmonized System code used for classifying goods in international trade.
				HsCode *string `json:"hsCode,omitempty"`

				// Quantity The number of units of a specific item.
				Quantity *float32 `json:"quantity,omitempty"`

				// Weight The weight of the Shipment.
				Weight *struct {
					// Unit The unit of measurement used for the weight of the Shipment.
					Unit CreateUpdateShipment201ItemsWeightUnit `json:"unit"`

					// Value The weight value.
					Value float32 `json:"value"`
				} `json:"weight,omitempty"`
			} `json:"items,omitempty"`

			// Receiver Represents the contact and address details of the receiver.
			Receiver struct {
				// City The city name of the address.
				City string `json:"city"`

				// CountryCode The country code of the address, typically in ISO 3166-1 alpha-2 format. For a full list of country codes, see the ISO website www.iso.org/obp/ui/#search
				CountryCode string `json:"countryCode"`

				// Email The email address of the person or company receiving the shipment.
				Email *string `json:"email,omitempty"`

				// Line1 The first line of the address, typically including street name and number.
				Line1 *string `json:"line1,omitempty"`

				// Line2 The second line of the address, typically used for additional information such as apartment or suite number.
				Line2 *string `json:"line2,omitempty"`

				// Line3 The third line of the address, often used for further details if needed.
				Line3 *string `json:"line3,omitempty"`

				// Name The name of the person or company receiving the shipment.
				Name string `json:"name"`

				// Phone The phone number of the person or company receiving the shipment. The phone number should be in international format, starting with a + followed by the country code, then the area code and local number.
				Phone string `json:"phone"`

				// PostCode The postal code or Zip Code of the address.
				PostCode *string `json:"postCode,omitempty"`

				// SecondPhone An additional phone number of the person or company receiving the shipment.
				SecondPhone *string `json:"secondPhone,omitempty"`

				// State The state or region of the address.
				State *string `json:"state,omitempty"`
			} `json:"receiver"`

			// Sender Represents the contact and address details of the sender.
			Sender struct {
				// City The city name of the address.
				City string `json:"city"`

				// CountryCode The country code of the address, typically in ISO 3166-1 alpha-2 format. For a full list of country codes, see the ISO website www.iso.org/obp/ui/#search
				CountryCode string `json:"countryCode"`

				// Email The email address of the person or company sending the shipment.
				Email *string `json:"email,omitempty"`

				// Line1 The first line of the address, typically including street name and number.
				Line1 *string `json:"line1,omitempty"`

				// Line2 The second line of the address, typically used for additional information such as apartment or suite number.
				Line2 *string `json:"line2,omitempty"`

				// Line3 The third line of the address, often used for further details if needed.
				Line3 *string `json:"line3,omitempty"`

				// Name The name of the person or company sending the shipment.
				Name string `json:"name"`

				// Phone The phone number of the person or company sending the shipment. The phone number should be in international format, starting with a + followed by the country code, then the area code and local number.
				Phone string `json:"phone"`

				// PostCode The postal code or ZIP code of the address.
				PostCode *string `json:"postCode,omitempty"`

				// SecondPhone An additional phone number of the person or company sending the shipment.
				SecondPhone *string `json:"secondPhone,omitempty"`

				// State The state or region of the address.
				State *string `json:"state,omitempty"`
			} `json:"sender"`

			// TrackingNumber A unique code assigned by the shipping company to monitor and trace the shipment’s progress.
			TrackingNumber string `json:"trackingNumber"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *map[string][]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseCreateShipmentInvoiceResponse parses an HTTP response from a CreateShipmentInvoiceWithResponse call
func ParseCreateShipmentInvoiceResponse(rsp *http.Response) (*CreateShipmentInvoiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateShipmentInvoiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// ChargeableWeight The weight of the Shipment.
			ChargeableWeight struct {
				// Unit The unit of measurement used for the weight of the Shipment.
				Unit CreateShipmentInvoice201ChargeableWeightUnit `json:"unit"`

				// Value The weight value.
				Value float32 `json:"value"`
			} `json:"chargeableWeight"`

			// Charges The list of charges associated with the shipment.
			Charges []struct {
				// Amount Represents a monetary value including the currency and amount. For a full list of currency codes www.iso.org/iso-4217-currency-codes.html
				Amount struct {
					// Amount The amount of money, expressed as a decimal value. Must be 0 or more.
					Amount float32 `json:"amount"`

					// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters long and must be a valid currency code as defined by the system.
					CurrencyCode string `json:"currencyCode"`
				} `json:"amount"`

				// Type The type of the charge. All applicable costs associated with the Shipment. Possible values are; Base Rate, fuel Surcharge, insurance, War risk, handling and packing fees, and other charges. It can not exceed 100 characters
				Type string `json:"type"`
			} `json:"charges"`

			// Invoice Represents the details of an invoice.
			Invoice struct {
				// BillingAccountName The billing account name associated with the invoice. Must not exceed 500 characters.
				BillingAccountName string `json:"billingAccountName"`

				// BillingAccountNumber The billing account number associated with the invoice. Must not exceed 100 characters.
				BillingAccountNumber string `json:"billingAccountNumber"`

				// CurrencyCode The three-letter ISO currency code. Must be exactly 3 characters and valid.
				CurrencyCode string `json:"currencyCode"`

				// InvoiceDate The date and time of the invoice.
				InvoiceDate time.Time `json:"invoiceDate"`

				// InvoiceNumber The invoice number of the shipment. Must not exceed 100 characters.
				InvoiceNumber string `json:"invoiceNumber"`

				// TaxAmount The tax amount applied to the invoice. Must be 0 or more.
				TaxAmount float32 `json:"taxAmount"`

				// TotalAmountIncludingTax The total amount including tax for the invoice. Must be 0 or more and greater than the TaxAmount.
				TotalAmountIncludingTax float32 `json:"totalAmountIncludingTax"`

				// TotalDiscountAmount The total discount amount applied to the invoice. Must be 0 or more.
				TotalDiscountAmount *float32 `json:"totalDiscountAmount,omitempty"`
			} `json:"invoice"`

			// TrackingNumber The unique tracking number associated with the shipment.
			TrackingNumber string `json:"trackingNumber"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors  *map[string][]string `json:"errors,omitempty"`
			Message *string              `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
